name: Railway Deploy
on:
  push:
    branches:
      - main
      - ng/fix-server
jobs:
  deploy:
    name: Deploy Sync Server
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{ vars.RAILWAY_SERVICE_ID_PRODUCTION_TESTNET }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PRODUCTION_TESTNET }}
    steps:
      - uses: actions/checkout@v4
      # Update the cache mount ID in the Dockerfile to include the service-specific pnpm store
      - run: sed -i 's|\(--mount=type=cache,id=\)workspace|\1s/${{ env.SVC_ID }}-pnpm-store|' Dockerfile
      - run: railway up --service=${{ env.SVC_ID }}
